// Generated by scripts/gen-config.mjs from .env — do not edit by hand,
// do not commit (see .gitignore). Edit .env and re-run the script instead.
export const CONFIG = {
  SUPABASE_URL: '',
  SUPABASE_ANON_KEY: '',
  GEMINI_API_KEY: '',
  GEMINI_MODEL: 'gemini-3.5-flash-lite',
  GEMINI_ENDPOINT: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent',
  FORCE_DEMO: false,
  FORCE_DEMO_AI: false,
  AI_DAILY_BUDGET: 200,
  AI_FALLBACK_URL: 'https://api.groq.com/openai/v1/chat/completions',
  AI_FALLBACK_KEY: '',
  AI_FALLBACK_MODEL: 'openai/gpt-oss-120b',
};
//скопируйте это и переменуйте в config.js, затем заполните значения из .env