// Generated by scripts/gen-config.mjs from .env — do not edit by hand,
// do not commit (see .gitignore). Edit .env and re-run the script instead.
export const CONFIG = {
  SUPABASE_URL: 'https://rzjposqkjfycmtckzmne.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6anBvc3FramZ5Y210Y2t6bW5lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxNzM2NTcsImV4cCI6MjEwMjc0OTY1N30.U1bS7LnfPS4E_dTRFV38z4yx7SbU0vyjv0qQd5mDrLk',
  GEMINI_API_KEY: 'AQ.Ab8RN6I8-N6MRSSHZ0WsKMoN-HEBuUrxuaizQJLfW6fOwg3JHA',
  GEMINI_MODEL: 'gemini-3.5-flash-lite',
  GEMINI_ENDPOINT: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent',
  FORCE_DEMO: false,
  FORCE_DEMO_AI: false,
  AI_DAILY_BUDGET: 200,
  AI_FALLBACK_URL: 'https://api.groq.com/openai/v1/chat/completions',
  AI_FALLBACK_KEY: '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',
  AI_FALLBACK_MODEL: 'openai/gpt-oss-120b',
};
