// scripts/gen-config.mjs — reads .env and writes config.js. Run this after
// every edit to .env: `node scripts/gen-config.mjs`. No dependencies.
//
// This is the local-dev equivalent of what render-build.sh does at deploy time
// from Render's own environment variables — same shape, same rule: the Gemini
// key never gets written into a config.js meant to be served publicly.
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const envPath = join(root, '.env');

if (!existsSync(envPath)) {
  console.error('No .env found. Copy .env.example to .env and fill in real values first.');
  process.exit(1);
}

const env = {};
for (const line of readFileSync(envPath, 'utf8').split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eq = trimmed.indexOf('=');
  if (eq === -1) continue;
  env[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
}

const model = env.GEMINI_MODEL || 'gemini-3.5-flash-lite';
const config = `// Generated by scripts/gen-config.mjs from .env — do not edit by hand,
// do not commit (see .gitignore). Edit .env and re-run the script instead.
export const CONFIG = {
  SUPABASE_URL: '${env.SUPABASE_URL || ''}',
  SUPABASE_ANON_KEY: '${env.SUPABASE_ANON_KEY || ''}',
  GEMINI_API_KEY: '${env.GEMINI_API_KEY || ''}',
  GEMINI_MODEL: '${model}',
  GEMINI_ENDPOINT: 'https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent',
  FORCE_DEMO: ${env.FORCE_DEMO === 'false' ? 'false' : 'true'},
  FORCE_DEMO_AI: ${env.FORCE_DEMO_AI === 'true' ? 'true' : 'false'},
  AI_DAILY_BUDGET: ${Number(env.AI_DAILY_BUDGET) > 0 ? Number(env.AI_DAILY_BUDGET) : 200},
  AI_FALLBACK_URL: '${env.AI_FALLBACK_URL || ''}',
  AI_FALLBACK_KEY: '${env.AI_FALLBACK_KEY || ''}',
  AI_FALLBACK_MODEL: '${env.AI_FALLBACK_MODEL || ''}',
};
`;

writeFileSync(join(root, 'config.js'), config);
console.log('wrote config.js from .env (FORCE_DEMO=%s, FORCE_DEMO_AI=%s, GEMINI_API_KEY=%s, backup provider=%s)',
  env.FORCE_DEMO === 'false' ? 'false' : 'true',
  env.FORCE_DEMO_AI === 'true' ? 'true' : 'false',
  env.GEMINI_API_KEY ? 'set' : 'empty',
  (env.AI_FALLBACK_URL && env.AI_FALLBACK_KEY && env.AI_FALLBACK_MODEL) ? env.AI_FALLBACK_MODEL : 'none');
